version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: buea_webapp
    ports:
      - "80:80"
    volumes:
      - ./webapp:/var/www/html
      - ./php-config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=buea_einwahl
      - DB_USER=buea_user
      - DB_PASS=buea_password
    command: >
      bash -c "
      docker-php-ext-install pdo pdo_mysql mysqli &&
      a2enmod rewrite &&
      apache2-foreground
      "

  db:
    image: mariadb:10.11
    container_name: buea_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: buea_einwahl
      MYSQL_USER: buea_user
      MYSQL_PASSWORD: buea_password
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  db_data: